### ISSUE TITLE
Change the login/logout messages

### ISSUE THREAD

**Issue by Photon-GitHub** [Photon-GitHub/Owl-Planet#10]
The current ones look very childish.

**Comment by TheLordAlduin** [comment]
Join And Leave Message Removed for normal users .
added join messages for other ranks

**Comment by TheLordAlduin** [comment]
you should give this permissions to each group
for admin:
**deluxejoin.format.admin**
management:
**deluxejoin.format.management**
moderators:
**deluxejoin.format.mod
deluxejoin.format.srmod**
supporter:
**deluxejoin.format.supporter**

**Comment by Photon-GitHub** [comment]
Done
![unbenannt](https://cloud.githubusercontent.com/assets/22870297/21278018/44e88234-c3d9-11e6-89a5-0df5856501fd.PNG)
