### ISSUE TITLE
Tablist Prefixes Bug

### ISSUE THREAD

**Issue by TheLordAlduin** [Photon-GitHub/Owl-Planet#12]
RQz170 Joined Server And Management Prefix was too long . the name was not appearing correctly 
so we should short prefixes like [A]
@Photon-GitHub 
i have sent screen shot on our discord channel

**Comment by TheLordAlduin** [comment]
Fixed By TheLordAlduin

**Comment by Photon-GitHub** [comment]
I will check this and replace the group prefixes that are longer than 16 chars with a shorter name. E.g. Admin can stay the same.
