### ISSUE TITLE
Map bug

### ISSUE THREAD

**Issue by Photon-GitHub** [Photon-GitHub/Owl-Planet#5]
See yourself.
Either edit the image or fix the position.
![unbenannt](https://cloud.githubusercontent.com/assets/22870297/21104919/98a40424-c088-11e6-80ec-21d1b28bc2af.PNG)

**Comment by TheLordAlduin** [comment]
we will place logo here . this picture is just for test

**Comment by TheLordAlduin** [comment]
Done
